
[[redirects]]
  from = "/gamelift-pb/latest/*"
  to = "https://d3ap7k91xazrkc.cloudfront.net/0.1.5/:splat"
  status = 200

[[redirects]]
  from = "/gamelift-pb/0.1.3/*"
  to = "https://d3ap7k91xazrkc.cloudfront.net/0.1.3/:splat"
  status = 200

[[redirects]]
  from = "/gamelift-pb/0.1.4/*"
  to = "https://d3ap7k91xazrkc.cloudfront.net/0.1.4/:splat"
  status = 200

[[redirects]]
  from = "/gamelift-pb/0.1.5/*"
  to = "https://d3ap7k91xazrkc.cloudfront.net/0.1.5/:splat"
  status = 200
