
[[redirects]]
  from = "/gamelift-pb/latest"
  to = "/gamelift-pb/0.1.3"
  status = 200

[[redirects]]
  from = "/gamelift-pb/0.1.3"
  to = "https://d3ap7k91xazrkc.cloudfront.net/0.1.3"
  status = 200
